# Project Metadata
spring.application.name=workforceportal
server.port=8080
server.address=0.0.0.0

# MongoDB Atlas Configuration

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=workforce_db

# JWT Security Settings

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

logging.level.org.springframework.data.mongodb=DEBUG

# MONGODB_URI=mongodb+srv://therealanimeguy21_db_user:8BF7qda619Gl508z@it342.6tcmz6y.mongodb.net/?appName=IT342 
JWT_SECRET=7d5a3f2b1e9c8d7b6a5e4f3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b